=== lifeXmatter/WSDCIA/index.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="Company">
		<xsd:complexType>
		
		<xsd:element name="Employee">
			<xsd:complexType>
				<xsd:sequence>
					<xsd:element name="emp-name" type="xs:string"/>
					<xsd:element name="emp-age" type="xs:integer"/>
					<xsd:element name="emp-salary" type="xs:integer"/>
					<xsd:element name="emp-emailid" type="xs:string"/>
					<xsd:element name="emp-phonenum" type="xs:integer"/>
					<xsd:element name="emp-designation" type="xs:string"/>
					
				</xsd:sequence>	
			</xsd:complexType>
		</xsd:element>

	</xsd:complexType>
	</xsd:element>
<xsd:simpleType name="emp-salary">
  <xsd:restriction base="xs:integer">
    <xsd:minInclusive value="50000"/>
    <xsd:maxInclusive value="200000"/>
  </xsd:restriction>
</xsd:simpleType>
</xsd:schema>

=== lifeXmatter/WSDCIA/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="index.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="index.xsd">
	<Employee>
		<emp-name>Matt Dameon</emp-name>
		<emp-age>37</emp-age>
		<emp-salary>65000</emp-salary>
		<emp-emailid>mattdameon@company.com</emp-emailid>
		<emp-phonenum>761451678</emp-phonenum>
		<emp-designation>Junior Developer</emp-designation>
	</Employee>
	<Employee>
		<emp-name>Brad Pitt</emp-name>
		<emp-age>52</emp-age>
		<emp-salary>155000</emp-salary>
		<emp-emailid>bradpitt@company.com</emp-emailid>
		<emp-phonenum>641567867</emp-phonenum>
		<emp-designation>Lead Developer</emp-designation>
	</Employee>
	<Employee>
		<emp-name>Carla Simson</emp-name>
		<emp-age>29</emp-age>
		<emp-salary>51000</emp-salary>
		<emp-emailid>carlasimson@company.com</emp-emailid>
		<emp-phonenum>867519234</emp-phonenum>
		<emp-designation>Junior Developer</emp-designation>
	</Employee>
	<Employee>
		<emp-name>Riley Issac</emp-name>
		<emp-age>43</emp-age>
		<emp-salary>75000</emp-salary>
		<emp-emailid>rileyissac@company.com</emp-emailid>
		<emp-phonenum>678911223</emp-phonenum>
		<emp-designation>Associate Leader</emp-designation>
	</Employee>
	<Employee>
		<emp-name>Mark Kext</emp-name>
		<emp-age>47</emp-age>
		<emp-salary>90000</emp-salary>
		<emp-emailid>markkext@company.com</emp-emailid>
		<emp-phonenum>676761514</emp-phonenum>
		<emp-designation>Developer</emp-designation>
	</Employee>
</Company>
